name: textstats
version: 1.2.3
description: >
  Example about a webapp showing you text statistics.
author: Daniele Demichelis <daniele.demichelis@gmail.com>
homepage: https://github.com/danidemi/tutorial-dart
documentation: https://github.com/danidemi/tutorial-dart
dependencies:
  browser: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=0.8.10+6 <2.0.0"